//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV_ReportAnalytics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DV_ReportAnalytics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap area_chart_32 {
            get {
                object obj = ResourceManager.GetObject("area_chart_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DV_ReportAnalytics&gt;
        ///  &lt;Displays&gt;
        ///    &lt;RowInterpolation&gt;0&lt;/RowInterpolation&gt;
        ///    &lt;ColumnInterpolation&gt;0&lt;/ColumnInterpolation&gt;
        ///    &lt;MaximumItemsPerRow&gt;3&lt;/MaximumItemsPerRow&gt;
        ///    &lt;Tables&gt;
        ///      &lt;Item&gt;&lt;/Item&gt;
        ///    &lt;/Tables&gt;
        ///  &lt;/Displays&gt;
        ///&lt;/DV_ReportAnalytics&gt;.
        /// </summary>
        internal static string Displays_EPTReport {
            get {
                return ResourceManager.GetString("Displays_EPTReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_32 {
            get {
                object obj = ResourceManager.GetObject("folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_32 {
            get {
                object obj = ResourceManager.GetObject("help_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_32 {
            get {
                object obj = ResourceManager.GetObject("list_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DV_ReportAnalytics&gt;
        ///  &lt;Paths&gt;
        ///    &lt;Result&gt;&lt;/Result&gt;
        ///    &lt;Config&gt;&lt;/Config&gt;
        ///  &lt;/Paths&gt;
        ///&lt;/DV_ReportAnalytics&gt;
        ///.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DV_ReportAnalytics&gt;
        ///  &lt;Paths&gt;
        ///    &lt;Result&gt;&lt;/Result&gt;
        ///    &lt;Config&gt;&lt;/Config&gt;
        ///  &lt;/Paths&gt;
        ///  &lt;Settings&gt;&lt;/Settings&gt;
        ///  &lt;Displays&gt;&lt;/Displays&gt;
        ///&lt;/DV_ReportAnalytics&gt;.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_as_32 {
            get {
                object obj = ResourceManager.GetObject("save_as_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_32 {
            get {
                object obj = ResourceManager.GetObject("settings_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DV_ReportAnalytics&gt;
        ///  &lt;Settings&gt;
        ///    &lt;Type&gt;EPTReport&lt;/Type&gt;
        ///    &lt;Name&gt;EPT Report Results&lt;/Name&gt;
        ///    &lt;InputSheetName&gt;Results&lt;/InputSheetName&gt;
        ///    &lt;OutputSheetName&gt;CombinedResults&lt;/OutputSheetName&gt;
        ///    &lt;ResultFormat&gt;
        ///      &lt;Parameter&gt;Name_Speed_Torque&lt;/Parameter&gt;
        ///      &lt;Delimiter&gt;_&lt;/Delimiter&gt;
        ///      &lt;ParameterColumn&gt;0&lt;/ParameterColumn&gt;
        ///      &lt;ValueColumn&gt;3&lt;/ValueColumn&gt;
        ///    &lt;/ResultFormat&gt;
        ///  &lt;/Settings&gt;
        ///&lt;/DV_ReportAnalytics&gt;
        ///.
        /// </summary>
        internal static string Settings_EPTReport {
            get {
                return ResourceManager.GetString("Settings_EPTReport", resourceCulture);
            }
        }
    }
}
